chore: add support for driver cli args
appium/appium-base-driver pull request #486
Opened 2021-05-18 22:18 UTC by ayvnkhan

2021-05-18 22:30 UTC, jlipps approved these changes
this looks good. note that because of the monorepo work that @boneskull is doing, anything going into the 2.0 branch on this repo may need to go into appium/appium instead

2021-05-18 22:30 UTC, jlipps commented on lib/basedriver/driver.js
> +    //allow for cli args to be used by drivers
nit: `// ` (with space after)

2021-05-19 06:04 UTC, mykola-mokhnach commented on lib/basedriver/driver.js
> +  constructor (opts = {}, driverArgs = {}, shouldValidateCaps = true) {
this might break existing drivers. Consider adding a new argument to the end rather than in the middle

2021-05-19 06:10 UTC, mykola-mokhnach requested changes
a potential breaking change is present

2021-05-19 19:12 UTC, mykola-mokhnach approved these changes

2021-05-24 22:23 UTC, closed without merging